// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class DefaultSuiteTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void moduloServicio() {
    driver.get("https://www.choucairtesting.com/");
    driver.manage().window().setSize(new Dimension(1050, 708));
    {
      WebElement element = driver.findElement(By.linkText("Servicios"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("Servicios")).click();
  }
  @Test
  public void botonesPrincipales() {
    driver.get("https://www.choucairtesting.com/servicio/");
    driver.manage().window().setSize(new Dimension(1050, 708));
    driver.findElement(By.linkText("Capacidades")).click();
    driver.findElement(By.linkText("Cómo lo hacemos")).click();
    driver.findElement(By.linkText("Portafolio de Soluciones")).click();
  }
  @Test
  public void botonesSecundarios() {
    driver.get("https://www.choucairtesting.com/servicio/");
    driver.manage().window().setSize(new Dimension(1050, 708));
    driver.findElement(By.cssSelector(".has_eae_slider:nth-child(1) .elementor-element:nth-child(2) .elementor-animation-grow")).click();
    driver.findElement(By.cssSelector(".has_eae_slider:nth-child(2) .elementor-element:nth-child(2) .elementor-animation-grow")).click();
    driver.findElement(By.cssSelector(".has_eae_slider:nth-child(3) > .elementor-column-wrap .elementor-element:nth-child(2) .elementor-animation-grow")).click();
    driver.findElement(By.cssSelector(".has_eae_slider:nth-child(4) .elementor-element:nth-child(2) .elementor-animation-grow")).click();
    driver.findElement(By.cssSelector(".has_eae_slider:nth-child(5) .elementor-element:nth-child(2) .elementor-animation-grow")).click();
    driver.findElement(By.cssSelector(".has_eae_slider:nth-child(6) .elementor-element:nth-child(2) .elementor-animation-grow")).click();
    driver.findElement(By.linkText("Pruebas de Migración")).click();
    driver.findElement(By.linkText("Pruebas Generalistas")).click();
    driver.findElement(By.linkText("Automatización de Pruebas SAP")).click();
    driver.findElement(By.cssSelector(".has_eae_slider:nth-child(4) .elementor-element:nth-child(1) .elementor-animation-grow")).click();
    driver.findElement(By.cssSelector(".has_eae_slider:nth-child(5) .elementor-element:nth-child(1) .elementor-animation-grow")).click();
    driver.findElement(By.cssSelector(".has_eae_slider:nth-child(6) .elementor-element:nth-child(1) .elementor-animation-grow")).click();
    driver.findElement(By.linkText("Pruebas de Nómina")).click();
    driver.findElement(By.linkText("Pruebas de Seguridad")).click();
    driver.findElement(By.linkText("Alta automatización")).click();
    driver.findElement(By.linkText("Cursos y Certificaciones")).click();
  }
}
